name: Terraform

on:
    push:
        branches:
        - main

jobs:
  plan:
    name: Format Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Run terraform fmt check
        id: fmt
        run: terraform fmt -check -diff -recursive .

      - name: Initialize Terraform
        id: init
        run: |
          terraform init
      
      - name: Validate Terraform
        id: validate
        run: |
          terraform validate